/*
 * Copyright 2023 Andrew Jenkins <andrewjjenkins@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
"use strict";
const fs = require('fs');
const path = require('path');

const files = process.argv.slice(2);

const lines = [
    "// Autogenerated file (from tools/generateConst.js)",
    "",
];

for (let i = 0; i < files.length; i++) {
    const parsed = path.parse(files[i]);
    lines.push(`import ${parsed.name}_hex from "../../../${parsed.dir}/${parsed.name}";`);
}

lines.push("");
lines.push("const fromHexString = (hexString: string) =>");
lines.push("  Uint8Array.from(");
lines.push("    (hexString.split('\\n').join('').match(/.{1,2}/g) as RegExpMatchArray)");
lines.push("    .map((byte) => parseInt(byte, 16)));");
lines.push("");

lines.push("const consts = {");
for (let i = 0; i < files.length; i++) {
    const parsed = path.parse(files[i]);
    lines.push(`  ${parsed.name}: fromHexString(${parsed.name}_hex), `);
}
lines.push("};");
lines.push("export default consts;");
lines.push("");

fs.writeFileSync("src/generated/vm/consts.ts", lines.join('\n'));
